<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InternshipSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('internships')->insert([
            [
                'company_name'      => 'PT. Gojek Tokopedia',
                'position'          => 'Software Engineer Intern',
                'description'       => 'Bergabung dengan tim engineering Gojek untuk mengembangkan fitur-fitur baru pada platform menggunakan arsitektur microservices.',
                'vacancy_details'   => '3 Posisi · Hybrid · 3 Bulan',
                'job_description'   => json_encode([
                    'Mengembangkan fitur baru pada platform Gojek menggunakan microservices architecture.',
                    'Menulis unit test dan integration test untuk memastikan kualitas kode.',
                    'Berkolaborasi dengan tim Product dan Design dalam sprint planning.',
                    'Melakukan code review dan pair programming dengan senior engineers.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Teknik Informatika, Ilmu Komputer, atau sejenisnya.',
                'sistem_kerja'      => 'Hybrid',
                'location'          => 'Jakarta Selatan',
                'deadline'          => '2024-06-30',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'company_name'      => 'Telkomsel',
                'position'          => 'Marketing Communications Intern',
                'description'       => 'Bergabung dengan tim Marketing Telkomsel untuk menyusun strategi konten dan kampanye digital.',
                'vacancy_details'   => '2 Posisi · WFO (On-site) · 3 Bulan',
                'job_description'   => json_encode([
                    'Menyusun strategi konten media sosial untuk brand Telkomsel.',
                    'Membantu perencanaan dan eksekusi kampanye marketing digital.',
                    'Melakukan analisis kompetitor dan market research.',
                    'Membuat laporan performa kampanye secara berkala.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Ilmu Komunikasi, Marketing, atau sejenisnya.',
                'sistem_kerja'      => 'WFO (On-site)',
                'location'          => 'Jakarta Selatan',
                'deadline'          => '2024-06-30',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'company_name'      => 'Traveloka Indonesia',
                'position'          => 'UI/UX Designer Intern',
                'description'       => 'Bekerja dengan tim Product Design Traveloka untuk merancang antarmuka pengguna yang intuitif.',
                'vacancy_details'   => '2 Posisi · WFO (On-site) · 3 Bulan',
                'job_description'   => json_encode([
                    'Bekerja sama dengan tim Product Design dalam merancang antarmuka pengguna (UI) yang intuitif dan menarik untuk platform Traveloka.',
                    'Melakukan riset pengguna dan pengujian usability untuk mengidentifikasi area pengembangan pada produk yang sudah ada.',
                    'Membuat wireframe, prototype, dan desain high-fidelity menggunakan tool desain standar industri (Figma).',
                    'Menjaga konsistensi desain sesuai dengan Design System Traveloka.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Desain Komunikasi Visual, Teknik Informatika, atau sejenisnya.',
                'sistem_kerja'      => 'WFO (On-site)',
                'location'          => 'Jakarta Selatan',
                'deadline'          => '2024-06-30',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'company_name'      => 'PT. Microsoft',
                'position'          => 'Data Analyst Intern',
                'description'       => 'Bergabung dengan tim Data Analytics Microsoft Indonesia untuk menganalisis dataset dan membuat dashboard.',
                'vacancy_details'   => '2 Posisi · Hybrid · 6 Bulan',
                'job_description'   => json_encode([
                    'Menganalisis dataset besar untuk menghasilkan insight bisnis yang actionable.',
                    'Membuat dashboard dan visualisasi data menggunakan Power BI.',
                    'Mendukung tim product dalam A/B testing dan eksperimen.',
                    'Menulis query SQL untuk mengekstrak dan memanipulasi data.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Statistika, Matematika, Teknik Informatika, atau sejenisnya.',
                'sistem_kerja'      => 'Hybrid',
                'location'          => 'Jakarta Selatan',
                'deadline'          => '2024-06-30',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'company_name'      => 'PT. Google Indonesia',
                'position'          => 'Data Analyst Intern',
                'description'       => 'Mengembangkan pipeline data dan dashboard monitoring KPI untuk tim regional Google Indonesia.',
                'vacancy_details'   => '1 Posisi · Hybrid · 3 Bulan',
                'job_description'   => json_encode([
                    'Mengembangkan pipeline data untuk analisis performa produk Google di Indonesia.',
                    'Membangun dashboard otomatis untuk monitoring KPI tim regional.',
                    'Berkolaborasi dengan tim engineering untuk data quality improvement.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Statistika, Ilmu Komputer, atau sejenisnya.',
                'sistem_kerja'      => 'Hybrid',
                'location'          => 'Jakarta Selatan',
                'deadline'          => '2024-06-30',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'company_name'      => 'PT. Bank Central Asia',
                'position'          => 'Data Analyst Intern',
                'description'       => 'Bergabung dengan tim analytics BCA untuk menganalisis data transaksi nasabah dan mendukung risk management.',
                'vacancy_details'   => '2 Posisi · WFO (On-site) · 6 Bulan',
                'job_description'   => json_encode([
                    'Melakukan analisis data transaksi nasabah untuk identifikasi pola dan tren.',
                    'Membuat laporan dan dashboard performa bisnis untuk manajemen.',
                    'Mendukung tim risk management dalam pemodelan data.',
                    'Mengoptimalkan proses reporting melalui otomatisasi.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Statistika, Ekonomi, Teknik Informatika, atau sejenisnya.',
                'sistem_kerja'      => 'WFO (On-site)',
                'location'          => 'Jakarta Selatan',
                'deadline'          => '2024-06-30',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'company_name'      => 'PT. Indofood',
                'position'          => 'Data Analyst Intern',
                'description'       => 'Bergabung dengan tim Business Intelligence Indofood untuk menganalisis data penjualan dan distribusi produk.',
                'vacancy_details'   => '1 Posisi · WFO (On-site) · 3 Bulan',
                'job_description'   => json_encode([
                    'Menganalisis data penjualan dan distribusi produk Indofood secara nasional.',
                    'Membuat laporan mingguan performa sales per region.',
                    'Mendukung tim supply chain dalam forecasting demand.',
                    'Membangun visualisasi data untuk presentasi ke stakeholder.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Teknik Industri, Statistika, Manajemen, atau sejenisnya.',
                'sistem_kerja'      => 'WFO (On-site)',
                'location'          => 'Jakarta Selatan',
                'deadline'          => '2024-06-30',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'company_name'      => 'Traveloka Indonesia',
                'position'          => 'UI/UX Designer Intern',
                'description'       => 'Posisi kedua di kantor Traveloka Tangerang untuk tim Product Design.',
                'vacancy_details'   => '2 Posisi · WFO (On-site) · 3 Bulan',
                'job_description'   => json_encode([
                    'Bekerja sama dengan tim Product Design dalam merancang antarmuka pengguna (UI) yang intuitif dan menarik untuk platform Traveloka.',
                    'Melakukan riset pengguna dan pengujian usability untuk mengidentifikasi area pengembangan pada produk yang sudah ada.',
                    'Membuat wireframe, prototype, dan desain high-fidelity menggunakan tool desain standar industri (Figma).',
                    'Menjaga konsistensi desain sesuai dengan Design System Traveloka.',
                ]),
                'minimum_education' => 'S1 Mahasiswa Aktif (Semester 6 ke atas) - Desain Komunikasi Visual, Teknik Informatika, atau sejenisnya.',
                'sistem_kerja'      => 'WFO (On-site)',
                'location'          => 'Tangerang',
                'deadline'          => '2024-07-15',
                'is_active'         => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ]);
    }
}
